package geom;

/**
 * Type of geometrical object.
 * @author alexeev
 */
public enum GeomType {
  ANGLE3D,
  ARC3D,
  CIRCLE3D,
  CONE3D,
  CONE_SECTION3D,
  CUBE3D,
  CYLINDER3D,
  CYLINDER_SECTION3D,
  DODECAHEDRON3D,
  ELLIPSE3D,
  DODECAHEDRON_ELONGATED3D,
  HYPERBOLE3D,
  ICOSAHEDRON3D,
  LINE3D,
  MENGER,
  OCTAHEDRON3D,
  PARABOLA3D,
  PLANE3D,
  POLYGON3D,
  ELEMENTARYFUNCTION2D,
  PRISM3D,
  PYRAMID3D,
  RAY3D,
  DODECAHEDRON_ROMBIC3D,
  RIB3D,
  SECTOR3D,
  SIMPLEX3D,
  SPHERE3D,
  TRIANG3D,
  OCTAHEDRON_TRUNCATED3D,
  VECT3D,
  ELLIPSOID3D,
  ELLIPTIC_PARABOLOID3D,
  HYPERBOLOID_OF_ONE_SHEET3D,
  HYPERBOLOID_OF_TWO_SHEET3D,
  PAIROFLINES3D,
  STELLAR_OCTAHEDRON;
}
