package tasks;

public enum Taxon {
    GENERAL_PROBLEMS,
    TRIANGLE_PROBLEMS,
    MIDPOINT_PROBLEMS,
    PERPENDICULAR_PROBLEMS,
    BISECTOR_PROBLEMS,
    ANGEL_PROBLEMS,
    QUADRILATERAL_PROBLEMS
}
